basePath: /api
definitions:
  service.BuildAndPushImageInfo:
    properties:
      activeDeadlineSeconds:
        description: Job存活时间
        type: integer
      info:
        allOf:
        - $ref: '#/definitions/service.buildImageInfo'
        description: 构建并推送镜像的具体信息
      name:
        description: 唯一名称
        maxLength: 32
        type: string
      podNameSelector:
        allOf:
        - $ref: '#/definitions/service.PodNameSelector'
        description: Pod名称调度
      resource:
        allOf:
        - $ref: '#/definitions/service.CommonWorkLoadResource'
        description: 工作负载资源
    required:
    - info
    - name
    - podNameSelector
    - resource
    type: object
  service.Builder:
    properties:
      command:
        description: 启动命令
        items:
          type: string
        type: array
      env:
        additionalProperties:
          type: string
        description: 环境变量
        type: object
      image:
        description: 镜像
        type: string
      name:
        description: 唯一名称
        maxLength: 36
        type: string
      nfs:
        description: nfs配置
        items:
          $ref: '#/definitions/types.NFS'
        type: array
      privateBuilder:
        allOf:
        - $ref: '#/definitions/service.DedicatedBuilder'
        description: 私有构建机配置
      registry:
        allOf:
        - $ref: '#/definitions/types.Registry'
        description: 镜像凭证
      resource:
        allOf:
        - $ref: '#/definitions/service.CommonWorkLoadResource'
        description: 工作负载资源
      specialBuilder:
        allOf:
        - $ref: '#/definitions/service.DedicatedBuilder'
        description: 特殊构建机配置
    required:
    - image
    - name
    - resource
    type: object
  service.BuilderStart:
    properties:
      command:
        items:
          type: string
        type: array
      env:
        additionalProperties:
          type: string
        type: object
    type: object
  service.BuilderState:
    enum:
    - readyToRun
    - notExist
    - pending
    - running
    - succeeded
    - failed
    - unknown
    type: string
    x-enum-varnames:
    - BuilderReadyToRun
    - BuilderNotExist
    - BuilderPending
    - BuilderRunning
    - BuilderSucceeded
    - BuilderFailed
    - BuilderUnknown
  service.BuilderStatus:
    properties:
      message:
        type: string
      status:
        $ref: '#/definitions/service.BuilderState'
    type: object
  service.CommonWorkLoadResource:
    properties:
      limitCpu:
        description: 最大CPU
        type: string
      limitDisk:
        description: 最大磁盘容量
        type: string
      limitDiskIO:
        description: 最大磁盘容量
        type: string
      limitMem:
        description: 最大内存
        type: string
      requestCPU:
        description: 最小CPU
        type: string
      requestDisk:
        description: 最小磁盘容量
        type: string
      requestDiskIO:
        description: 最小磁盘IO
        type: string
      requestMem:
        description: 最小内存
        type: string
    required:
    - limitCpu
    - limitDisk
    - limitDiskIO
    - limitMem
    - requestCPU
    - requestDisk
    - requestDiskIO
    - requestMem
    type: object
  service.DedicatedBuilder:
    properties:
      name:
        type: string
    type: object
  service.Job:
    properties:
      activeDeadlineSeconds:
        description: Job存活时间
        type: integer
      command:
        description: 启动命令
        items:
          type: string
        type: array
      env:
        additionalProperties:
          type: string
        description: 环境变量
        type: object
      image:
        description: 镜像
        type: string
      name:
        description: 唯一名称
        maxLength: 36
        type: string
      nfs:
        description: nfs配置
        items:
          $ref: '#/definitions/types.NFS'
        type: array
      podNameSelector:
        allOf:
        - $ref: '#/definitions/service.PodNameSelector'
        description: Pod名称调度选项
      registry:
        allOf:
        - $ref: '#/definitions/types.Registry'
        description: 镜像凭证
      resource:
        allOf:
        - $ref: '#/definitions/service.CommonWorkLoadResource'
        description: 工作负载资源
    required:
    - image
    - name
    - resource
    type: object
  service.JobState:
    enum:
    - pending
    - running
    - succeeded
    - failed
    - unknown
    type: string
    x-enum-varnames:
    - JobPending
    - JobRunning
    - JobSucceeded
    - JobFailed
    - JobUnknown
  service.JobStatus:
    properties:
      message:
        type: string
      podIp:
        type: string
      state:
        $ref: '#/definitions/service.JobState'
    type: object
  service.PodNameSelector:
    properties:
      selector:
        description: Pod名称，调度到指定pod
        type: string
      usePodData:
        description: 使用和podNameSelector相同的data目录，当挂载目录使用hostPath时依赖PodNameSelector
        type: boolean
    required:
    - selector
    type: object
  service.RemotingGitRepo:
    properties:
      gitRepoName:
        type: string
      gitRepoRef:
        type: string
    type: object
  service.RemotingUrls:
    properties:
      apiUrl:
        type: string
      sshUrl:
        type: string
      webVscodeUrl:
        type: string
    type: object
  service.RemotingUserFile:
    properties:
      from:
        type: string
      to:
        type: string
    type: object
  service.RemotingWorkspace:
    properties:
      gitEmail:
        type: string
      gitRepo:
        $ref: '#/definitions/service.RemotingGitRepo'
      gitUsername:
        type: string
      remotingYamlName:
        type: string
      userEnvs:
        additionalProperties:
          type: string
        type: object
      userFiles:
        items:
          $ref: '#/definitions/service.RemotingUserFile'
        type: array
      userId:
        type: string
      workspaceId:
        type: string
    type: object
  service.TaskId:
    properties:
      taskId:
        type: string
    type: object
  service.TaskStatus:
    properties:
      detail:
        type: string
      status:
        $ref: '#/definitions/types.TaskState'
    type: object
  service.buildImageInfo:
    properties:
      buildArgs:
        additionalProperties:
          type: string
        description: 构建参数
        type: object
      contextPath:
        description: 构建代码上下文路径
        type: string
      destinations:
        description: 推送镜像完整目标包含仓库地址和tag，例如 xxxx/xxx-hub:v1
        items:
          type: string
        type: array
      dockerFilePath:
        description: dockerfile路径
        type: string
      registries:
        description: 推送镜像需要的凭据
        items:
          $ref: '#/definitions/types.Registry'
        type: array
    required:
    - contextPath
    - destinations
    - dockerFilePath
    - registries
    type: object
  types.NFS:
    properties:
      mountPath:
        type: string
      path:
        type: string
      server:
        type: string
    type: object
  types.Registry:
    properties:
      password:
        type: string
      server:
        type: string
      username:
        type: string
    type: object
  types.Result:
    properties:
      data: {}
      message:
        type: string
      status:
        type: integer
    type: object
  types.TaskState:
    enum:
    - waiting
    - running
    - succeeded
    - failed
    - unknown
    type: string
    x-enum-varnames:
    - TaskWaiting
    - TaskRunning
    - TaskSucceeded
    - TaskFailed
    - TaskUnknown
info:
  contact: {}
  title: kubernetes-manager api文档
  version: 0.0.1
paths:
  /builders:
    post:
      consumes:
      - application/json
      parameters:
      - description: 凭证信息
        in: header
        name: Devops-Token
        required: true
        type: string
      - description: 构建机信息
        in: body
        name: builder
        required: true
        schema:
          $ref: '#/definitions/service.Builder'
      responses:
        "200":
          description: 任务ID
          schema:
            allOf:
            - $ref: '#/definitions/types.Result'
            - properties:
                data:
                  $ref: '#/definitions/service.TaskId'
              type: object
      summary: 创建构建机
      tags:
      - builder
  /builders/{builderName}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: 凭证信息
        in: header
        name: Devops-Token
        required: true
        type: string
      - description: 构建机名称
        in: path
        name: builderName
        required: true
        type: string
      responses:
        "200":
          description: 任务ID
          schema:
            allOf:
            - $ref: '#/definitions/types.Result'
            - properties:
                data:
                  $ref: '#/definitions/service.TaskId'
              type: object
      summary: 删除构建机
      tags:
      - builder
  /builders/{builderName}/start:
    put:
      consumes:
      - application/json
      parameters:
      - description: 凭证信息
        in: header
        name: Devops-Token
        required: true
        type: string
      - description: 构建机名称
        in: path
        name: builderName
        required: true
        type: string
      - description: 构建机启动信息
        in: body
        name: builder
        required: true
        schema:
          $ref: '#/definitions/service.BuilderStart'
      responses:
        "200":
          description: 任务ID
          schema:
            allOf:
            - $ref: '#/definitions/types.Result'
            - properties:
                data:
                  $ref: '#/definitions/service.TaskId'
              type: object
      summary: 启动构建机
      tags:
      - builder
  /builders/{builderName}/status:
    get:
      consumes:
      - application/json
      parameters:
      - description: 凭证信息
        in: header
        name: Devops-Token
        required: true
        type: string
      - description: 构建机名称
        in: path
        name: builderName
        required: true
        type: string
      responses:
        "200":
          description: 构建机状态
          schema:
            allOf:
            - $ref: '#/definitions/types.Result'
            - properties:
                data:
                  $ref: '#/definitions/service.BuilderStatus'
              type: object
      summary: 获取构建机状态
      tags:
      - builder
  /builders/{builderName}/stop:
    put:
      consumes:
      - application/json
      parameters:
      - description: 凭证信息
        in: header
        name: Devops-Token
        required: true
        type: string
      - description: 构建机名称
        in: path
        name: builderName
        required: true
        type: string
      responses:
        "200":
          description: 任务ID
          schema:
            allOf:
            - $ref: '#/definitions/types.Result'
            - properties:
                data:
                  $ref: '#/definitions/service.TaskId'
              type: object
      summary: 停止构建机
      tags:
      - builder
  /builders/{builderName}/terminal:
    get:
      consumes:
      - application/json
      parameters:
      - description: 凭证信息
        in: header
        name: Devops-Token
        required: true
        type: string
      - description: 构建机名称
        in: path
        name: builderName
        required: true
        type: string
      responses:
        "200":
          description: 远程登录链接
          schema:
            allOf:
            - $ref: '#/definitions/types.Result'
            - properties:
                data:
                  type: string
              type: object
      summary: 获取远程登录链接
      tags:
      - builder
  /jobs:
    post:
      consumes:
      - application/json
      parameters:
      - description: 凭证信息
        in: header
        name: Devops-Token
        required: true
        type: string
      - description: JOB信息
        in: body
        name: job
        required: true
        schema:
          $ref: '#/definitions/service.Job'
      responses:
        "200":
          description: 任务ID
          schema:
            allOf:
            - $ref: '#/definitions/types.Result'
            - properties:
                data:
                  $ref: '#/definitions/service.TaskId'
              type: object
      summary: 创建JOB
      tags:
      - job
  /jobs/{jobName}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: 凭证信息
        in: header
        name: Devops-Token
        required: true
        type: string
      - description: JOB名称
        in: path
        name: jobName
        required: true
        type: string
      responses:
        "200":
          description: 任务ID
          schema:
            allOf:
            - $ref: '#/definitions/types.Result'
            - properties:
                data:
                  $ref: '#/definitions/service.TaskId'
              type: object
      summary: 删除JOB
      tags:
      - job
  /jobs/{jobName}/log:
    get:
      consumes:
      - application/json
      parameters:
      - description: 凭证信息
        in: header
        name: Devops-Token
        required: true
        type: string
      - description: JOB名称
        in: path
        name: jobName
        required: true
        type: string
      - description: 开始时间
        in: query
        name: sinceTime
        type: string
      responses:
        "200":
          description: JOB日志
          schema:
            allOf:
            - $ref: '#/definitions/types.Result'
            - properties:
                data:
                  type: string
              type: object
      summary: 获取JOB日志
      tags:
      - job
  /jobs/{jobName}/status:
    get:
      consumes:
      - application/json
      parameters:
      - description: 凭证信息
        in: header
        name: Devops-Token
        required: true
        type: string
      - description: JOB名称
        in: path
        name: jobName
        required: true
        type: string
      responses:
        "200":
          description: JOB状态
          schema:
            allOf:
            - $ref: '#/definitions/types.Result'
            - properties:
                data:
                  $ref: '#/definitions/service.JobStatus'
              type: object
      summary: 获取JOB状态
      tags:
      - job
  /jobs/buildAndPushImage:
    post:
      consumes:
      - application/json
      parameters:
      - description: 凭证信息
        in: header
        name: Devops-Token
        required: true
        type: string
      - description: 构建并推送镜像信息
        in: body
        name: builder
        required: true
        schema:
          $ref: '#/definitions/service.BuildAndPushImageInfo'
      responses:
        "200":
          description: 任务ID
          schema:
            allOf:
            - $ref: '#/definitions/types.Result'
            - properties:
                data:
                  $ref: '#/definitions/service.TaskId'
              type: object
      summary: 构建并推送镜像
      tags:
      - job
  /remoting/workspaces:
    post:
      consumes:
      - application/json
      parameters:
      - description: 凭证信息
        in: header
        name: Devops-Token
        required: true
        type: string
      - description: 工作空间信息
        in: body
        name: workspace
        required: true
        schema:
          $ref: '#/definitions/service.RemotingWorkspace'
      responses:
        "200":
          description: 任务ID
          schema:
            allOf:
            - $ref: '#/definitions/types.Result'
            - properties:
                data:
                  $ref: '#/definitions/service.TaskId'
              type: object
      summary: 创建工作空间
      tags:
      - remoting
  /remoting/workspaces/{workspaceId}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: 凭证信息
        in: header
        name: Devops-Token
        required: true
        type: string
      - description: 工作空间ID
        in: path
        name: workspaceId
        required: true
        type: string
      responses:
        "200":
          description: 任务ID
          schema:
            allOf:
            - $ref: '#/definitions/types.Result'
            - properties:
                data:
                  $ref: '#/definitions/service.TaskId'
              type: object
      summary: 删除工作空间
      tags:
      - remoting
  /remoting/workspaces/{workspaceId}/urls:
    get:
      consumes:
      - application/json
      parameters:
      - description: 凭证信息
        in: header
        name: Devops-Token
        required: true
        type: string
      - description: 工作空间ID
        in: path
        name: workspaceId
        required: true
        type: string
      responses:
        "200":
          description: url集合
          schema:
            allOf:
            - $ref: '#/definitions/types.Result'
            - properties:
                data:
                  $ref: '#/definitions/service.RemotingUrls'
              type: object
      summary: 获取远程开发相关路由
      tags:
      - remoting
  /tasks/{taskId}/status:
    get:
      consumes:
      - application/json
      parameters:
      - description: 凭证信息
        in: header
        name: Devops-Token
        required: true
        type: string
      - description: 任务ID
        in: path
        name: taskId
        required: true
        type: string
      responses:
        "200":
          description: 任务状态
          schema:
            allOf:
            - $ref: '#/definitions/types.Result'
            - properties:
                data:
                  $ref: '#/definitions/service.TaskStatus'
              type: object
      summary: 获取任务状态
      tags:
      - task
swagger: "2.0"
